Add configurable callback URL to 3-legged auth
ErikBoesen/schoolopy pull request #26
Opened 2021-01-26 23:26 UTC by gadhagod

You can now set a callback URL with the `request_authorization` function by setting the parameter `callback_url`.

2021-01-26 23:37 UTC, ErikBoesen requested changes

2021-01-26 23:37 UTC, ErikBoesen commented on schoolopy/authentication.py
> +            callback_url = self.DOMAIN_ROOT
Why not just include this in the function param? `...(self, callback_url=DOMAIN_ROOT):`

2021-01-26 23:38 UTC, ErikBoesen commented
Also, wow, eighth grade? Keep it up man, you're gonna do great things.

2021-01-26 23:39 UTC, ErikBoesen approved these changes

2021-01-26 23:39 UTC, ErikBoesen commented on schoolopy/authentication.py
> +            callback_url = self.DOMAIN_ROOT
Update: forgot that's dynamically set, this looks good

2021-01-26 23:39 UTC, merged

2021-01-27 02:01 UTC, gadhagod commented
Thanks! Congrats on becoming a SWE at schoology.