Add get_grading_period and get_grading_periods
ErikBoesen/schoolopy pull request #48
Opened 2022-06-27 00:46 UTC by CoderN-P

2022-07-08 05:36 UTC, ErikBoesen requested changes
Whoops, forgot to hit submit on this!

2022-07-08 15:49 UTC, CoderN-P commented on schoolopy/main.py
> +        return Assignment(self._post("/sections/%s/assignments" % section_id, assignment.json()))
Hi, thanks for replying. I will change to single quotes and test again later today.

2022-07-09 18:59 UTC, ErikBoesen commented on schoolopy/main.py
> +        return Assignment(self._post("/sections/%s/assignments" % section_id, assignment.json()))
Sounds good—I don't see any particular reason why it wouldn't work, after all.

2022-07-09 18:59 UTC, merged

2022-07-09 18:59 UTC, ErikBoesen commented
Thank you so much for your contribution!

2022-07-09 19:00 UTC, CoderN-P commented
Thank you for making this amazing lib too!